runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.* 
  script: main.app

resources:
  memory_gb: 2.0  
  
libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: final-project-169218:us-central1:final-project-mysql
    CLOUDSQL_USER: habhakta
    CLOUDSQL_PASSWORD: Jitudipu94
    SERVER_SOFTWARE: ''
# [END env_variables]